import streamlit as st
def translate(text, lang):
    return translations.get(lang, {}).get(text, text)
 
translations = {
    'English': {
        'Budget Planner': 'Budget Planner',
        'Please Login to continue.': 'Please Login to continue.',        'Password': 'Password',
        'Login': 'Login',
        'Login Successful!':'Login Successful!',
        'Logout': 'Logout',
        'Invalid username or password': 'Invalid username or password',
        'Hello': 'Hello',
        'Income': 'Income',
        'Expense': 'Expense',
        'Leftover': 'Leftover',
        'Add Income': 'Add Income',
        'Add Expense': 'Add Expense',
        'Update': 'Update',
        'Financial Goals:': 'Financial Goals',
        'save for investment': 'save for investment',
        'Generate': 'Generate',
        'Home':'Home',
        'Crypto':'Crypto',
        'Features':'Features',
        'Get most out of your money and investments with the power of AI!':'Get most out of your money and investments with the power of AI!',
        'Investments':'Investments',
        'Investments %':'Investments %',
        'Be Investment Ready':'Be Investment Ready',
        'Market Insights':'Market Insights',
        'Get Market Insights':'Get Market Insights',
        'Tracker':'Tracker',
        'Track your investment goals':'Track your investment goals',
        'Portfolio':'Portfolio',
        'Build your financial portfolio':'Build your financial portfolio',
        'DASHBOARD':'DASHBOARD',
        'INVESTMENTS':'INVESTMENTS',
        'MARKET INSIGHTS':'MARKET INSIGHTS',
        'BUDGET PLANNER' : 'BUDGET PLANNER',
        'REPORT GENERATION':'REPORT GENERATION',
        'NEWS SENTIMENT ANALYSIS':'NEWS SENTIMENT ANALYSIS',
        'AGENTS':'AGENTS',
        'LOG OUT':'LOG OUT',
        'Total Investments':'Total Investments',
        'Stocks':'Stocks',
        'Your Stocks':'Your Stocks',
        'Top Stocks':'Top Stocks',
        'Top Crypto':'Top Crypto',
        'Price':'Price',
        'Symbol':'Symbol',
        'Bar chart of Prices': 'Bar chart of Prices',
        'Expenses': 'Expenses',
        'Update Income': 'Update Income',
        'Update Expense': 'Update Expense',
        'Summary': 'Summary',
        'Total Investments in stocks': 'Total Investments in stocks',
        'Total Investments in crypto': 'Total Investments in crypto',
        'Get Stocks Value': 'Get Stocks Value',
        'Get Crypto Value': 'Get Crypto Value',
        'Stock Name': 'Stock Name',
        'Crypto Name': 'Crypto Name',
        'Stocks Quantity': 'Stocks Quantity',
        'Crypto Quantity': 'Crypto Quantity',
        'Purchase Stock': 'Purchase Stock',
        'Purchase Crypto': 'Purchase Crypto',
        'Stocks Summary': 'Stocks Summary',
        'Crypto Summary': 'Crypto Summary',
        'AI SUMMARY': 'AI SUMMARY',
        'Data': 'Data',
        'Fetch':'Fetch',
        'Graph': 'Graph',
        'Your Crypto':'Your Crypto',
        'Market Trends': 'Market Trends',
        'Investment Opportunities': 'Investment Opportunities',
        'Risk Warnings': 'Risk Warnings',
        'generate report': 'generate report',
        'News Sentiment Stock Prediction': 'News Sentiment Stock Prediction',
        'Enter Stock Name': 'Enter Stock Name',
        'Fetch News & Analyze Sentiment': 'Fetch News & Analyze Sentiment',
        'Ask AI Financial Assistant': 'Ask AI Financial Assistant',
        'Ask about stock trends, investments, or finance!': 'Ask about stock trends, investments, or finance!',
        'Get Insights': 'Get Insights',
        'Adding this expense will make your leftover negative. Please adjust the amount.':'Adding this expense will make your leftover negative. Please adjust the amount.',
        'Profit/Loss':'Profit/Loss',
        'Purchase':'Purchase',
    },
    'Hindi': {
        'Fetch':'लाना',
        'Purchase':'खरीदें',
        'Budget Planner': 'बजट योजनाकार',
        'Please Login to continue.': 'कृपया जारी रखने के लिए लॉगिन करें।',
        'Username': 'उपयोगकर्ता नाम',
        'Password': 'पासवर्ड',
        'Login': 'लॉगिन',
        'Login Successful!':'लॉगिन सफल!',
        'Logout': 'लॉगआउट',
        'Invalid username or password': 'अमान्य उपयोगकर्ता नाम या पासवर्ड',
        'Hello': 'नमस्ते',
        'Income': 'आमदनी',
        'Expense': 'खर्च',
        'Leftover': 'बचा हुआ',
        'Add Income': 'आमदनी जोड़ें',
        'Add Expense': 'खर्च जोड़ें',
        'Update': 'अपडेट',
        'Financial Goals:': 'वित्तीय लक्ष्य',
        'save for investment': 'निवेश के लिए बचत करें',
        'Generate': 'उत्पन्न करें',
        'Home': 'होम',
        'Features':'विशेषताएँ',
        'Get most out of your money and investments with the power of AI!':'अपना पैसा और निवेश अधिकतम रूप से अधिकतम करें एआई की ताकत के साथ!',
        'Investments':'निवेश',
        'Investments %':'निवेश %',
        'Be investment Ready':'निवेश के लिए तैयार रहें',
        'Market Insights':'बाज़ार की जानकारी',
        'Get Market Insights':'बाज़ार की जानकारी प्राप्त करें',
        'Tracker':'ट्रैकर',
        'Track your investment goals':'अपने निवेश लक्ष्यों का पता लगाएं',
        'Portfolio':'पोर्टफोलियो',
        'Build your financial portfolio':'अपने वित्तीय पोर्टफोलियो का निर्माण करें',
        'DASHBOARD':'डैशबोर्ड',
        'INVESTMENTS':'निवेश',
        'MARKET INSIGHTS':'बाजार की जानकारी',
        'BUDGET PLANNER':'बजट योजनाकार',
        'REPORT GENERATION':'रिपोर्ट जनरेशन',
        'NEWS SENTIMENT ANALYSIS':'समाचार भावना विश्लेषण',
        'AGENTS':'एजेंट्स',
        'LOG OUT':'लॉग आउट',
        'Total Investments':'कुल निवेश',
        'Stocks':'शेयर',
        'Your Stocks': 'आपके शेयर',
        'Your Crypto':'आपका क्रिप्टो',
        'Top Stocks':'शीर्ष शेयर',
        'Top Crypto':'शीर्ष क्रिप्टो',
        'Price':'कीमत',
        'Symbol':'चिह्न',
        'Bar chart of Prices': 'मूल्य का बार चार्ट',
        'Expenses': 'खर्चे',
        'Update Income': 'आय अपडेट करें',
        'Update Expense': 'खर्च अपडेट करें',
        'Summary': 'सारांश',
        'Total Investments in stocks': 'स्टॉक्स में कुल निवेश',
        'Total Investments in crypto': 'क्रिप्टो में कुल निवेश',
        'Get Stocks Value': 'स्टॉक्स का मूल्य प्राप्त करें',
        'Get Crypto Value': 'क्रिप्टो का मूल्य प्राप्त करें',
        'Stock Name': 'स्टॉक का नाम',
        'Crypto Name': 'क्रिप्टो का नाम',
        'Stocks Quantity': 'स्टॉक्स की मात्रा',
        'Crypto Quantity': 'क्रिप्टो की मात्रा',
        'Purchase Stock': 'स्टॉक खरीदें',
        'Purchase Crypto': 'क्रिप्टो खरीदें',
        'Stocks Summary': 'स्टॉक्स सारांश',
        'Crypto Summary': 'क्रिप्टो सारांश',
        'AI SUMMARY': 'एआई सारांश',
        'Data': 'डेटा',
        'Graph': 'ग्राफ',
        'Crypto':'क्रिप्टो',
        'Market Trends': 'बाजार के रुझान',
        'Investment Opportunities': 'निवेश के अवसर',
        'Risk Warnings': 'जोखिम चेतावनी',
        'generate report': 'रिपोर्ट तैयार करें',
        'News Sentiment Stock Prediction': 'समाचार भावना स्टॉक भविष्यवाणी',
        'Enter Stock Name': 'स्टॉक का नाम दर्ज करें',
        'Fetch News & Analyze Sentiment': 'समाचार प्राप्त करें और भावना का विश्लेषण करें',
        'Ask AI Financial Assistant': 'एआई वित्तीय सहायक से पूछें',
        'Ask about stock trends, investments, or finance!': 'स्टॉक रुझान, निवेश, या वित्त के बारे में पूछें!',
        'Get Insights': 'अवलोकन प्राप्त करें',
        'Adding this expense will make your leftover negative. Please adjust the amount.':'इस खर्च को जोड़ने से आपका शेष नकारात्मक हो जाएगा। कृपया राशि को समायोजित करें।',
        'Profit/Loss':'लाभ/हानि',
    },
    'French': {
        'Fetch':'Rapporter',
        'Purchase':'Achat',
        'Budget Planner': 'Planificateur budgétaire',
        'Please Login to continue.': 'Veuillez vous connecter pour continuer.',
        'Username':'nom d’utilisateur',
        'Password': 'mot de passe',
        'Login':'connectez-vous',
        'Login Successful!': 'Connexion réussie',
        'Logout': 'déconnexion',
        'Invalid username or password':'Nom d’utilisateur ou mot de passe non valide',
        'Hello':'Bonjour',
        'Income': 'Income',
        'Expense': 'revenu',
        'Leftover': 'reste',
        'Add Income': 'Ajouter un revenu',
        'Add Expense': 'Ajouter une dépense',
        'Update': 'mettre à jour',
        'Financial Goals:': 'Objectifs financiers:',
        'save for investment': 'Épargner pour investir',
        'Generate': 'Générer',
        'Home': 'Domicile',
        'Crypto':'Crypto',
        'Features':'Fonctionnalités',
        'Get most out of your money and investments with the power of AI!':'Tirez le meilleur parti de votre argent et de vos investissements grâce à la puissance de l’IA!',
        'Investments':'Investissements',
        'Be Investment Ready':'Soyez prêt à investir',
        'Market Insights':'Perspectives du marché',
        'Get Market Insights':'Obtenez des informations sur le marché',
        'Tracker':'Pisteur',
        'Track your investment goals':'Suivez vos objectifs de placement',
        'Portfolio':'Portefeuille',
        'Build your financial portfolio':'Construisez votre portefeuille financier',
        'DASHBOARD':'TABLEAU DE BORD',
        'INVESTMENTS':'INVESTISSEMENTS',
        'INVESTMENTS %':'INVESTISSEMENTS %',
        'MARKET INSIGHTS':'INFORMATIONS SUR LE MARCHÉ',
        'BUDGET PLANNER':'PLANIFICATEUR BUDGÉTAIRE',
        'REPORT GENERATION':'GÉNÉRATION DE RAPPORTS',
        'NEWS SENTIMENT ANALYSIS':'ANALYSE DU SENTIMENT D’ACTUALITÉ',
        'AGENTS':'AGENTS',
        'LOG OUT':'SE DÉCONNECTER',
        'Total Investments':'Total des investissements',
        'Stocks':'Actions',
        'Your Stocks': 'Vos actions',
        'Your Crypto': 'Votre crypto',
        'Top Stocks':'Meilleures actions',
        'Top Crypto':'Top Crypto',
        'Price':'Prix',
        'Symbol':'Symbole',
        'Bar chart of Prices': 'Diagramme en barres des prix',
        'Expenses': 'Dépenses',
        'Update Income': 'Mettre à jour le revenu',
        'Update Expense': 'Mettre à jour la dépense',
        'Summary': 'Résumé',
        'Total Investments in stocks': 'Investissements totaux en actions',
        'Total Investments in crypto': 'Investissements totaux en crypto',
        'Get Stocks Value': 'Obtenir la valeur des actions',
        'Get Crypto Value': 'Obtenir la valeur de la crypto',
        'Stock Name': 'Nom de l\'action',
        'Crypto Name': 'Nom de la crypto',
        'Stocks Quantity': 'Quantité d\'actions',
        'Crypto Quantity': 'Quantité de crypto',
        'Purchase Stock': 'Acheter des actions',
        'Purchase Crypto': 'Acheter des cryptos',
        'Stocks Summary': 'Résumé des actions',
        'Crypto Summary': 'Résumé des cryptos',
        'AI SUMMARY': 'Résumé IA',
        'Data': 'Données',
        'Graph': 'Graphique',
        'Market Trends': 'Tendances du marché',
        'Investment Opportunities': 'Opportunités d\'investissement',
        'Risk Warnings': 'Avertissements de risque',
        'generate report': 'générer un rapport',
        'News Sentiment Stock Prediction': 'Prédiction des actions par sentiment des nouvelles',
        'Enter Stock Name': 'Entrer le nom de l\'action',
        'Fetch News & Analyze Sentiment': 'Récupérer les nouvelles et analyser le sentiment',
        'Ask AI Financial Assistant': 'Demander à l\'assistant financier IA',
        'Ask about stock trends, investments, or finance!': 'Demandez sur les tendances des actions, les investissements ou la finance!',
        'Get Insights': 'Obtenir des aperçus',
        'Adding this expense will make your leftover negative. Please adjust the amount.':'L’ajout de cette dépense rendra votre reste négatif. Veuillez ajuster le montant.',
        'Profit/Loss':'Bénéfices/Pertes',
    }
}